version: "2"
services:
    www:
        build: .
        image: app-service
        ports: 
            - 8080-8085:80
        volumes:
            - ./www:/var/www/html/
        links:
            - db:db
        networks:
            - default
        mem_limit: 536870912 #512 MB (Memory is measured in bytes and the minimum memory is 4 MB)
        cpu_shares: 100 #indicates 1 core
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: dbapp
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8081:80
        environment:
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root 
volumes:
    persistent: